tags_categorized = \
{
"60s": "time",
"70s": "time",
"80s": "time",
"aida vedisheva": "artist",
"alexander zatsepin": "composer",
"all tracks": "misc",
"alla pugachova": "artist",
"ambient": "genre",
"armenia": "region",
"art-rock": "genre",
"avilov": "artist",
"azerbaijan": "region",
"azerbayjan": "region",
"babayev": "artist",
"beat": "genre",
"belarus": "region",
"best": "misc",
"big beat": "genre",
"blues": "genre",
"boomerang": "artist",
"boris rychkov": "composer",
"bossa": "genre",
"composers": "misc",
"david goloschekin": "artist",
"dear boy": "misc",
"disco": "genre",
"disco band": "artist",
"dj jankie": "artist",
"dos-mukasan": "artist",
"easy": "genre",
"edita pyekha": "artist",
"electro": "genre",
"electron": "artist",
"electronica": "genre",
"eln": "artist",
"ensembles": "misc",
"eolika": "artist",
"estonia": "region",
"eurocrime": "genre",
"evgeny gevorgyan": "composer",
"fix": "artist",
"folk": "genre",
"funk": "genre",
"garage": "genre",
"garanian": "artist",
"garanyan": "artist",
"gennadiy gladkov": "artist",
"georgia": "region",
"gladkov": "composer",
"golubye gitary": "artist",
"gradsky": "artist",
"groove": "genre",
"groove beats": "genre",
"happy euro": "genre",
"igor brill": "artist",
"igor nazaruk": "artist",
"imants kalnins": "composer",
"info": "misc",
"isaac shwartz": "composer",
"iveriya": "artist",
"jaan kuman": "artist",
"jazz": "genre",
"jazz groove": "genre",
"jazz-funk": "genre",
"jazz-rock": "genre",
"kazakhstan": "region",
"konstantin orbelian": "artist",
"krylatov": "composer",
"kuman": "artist",
"kuprevicius": "composer",
"kyrgyzstan": "region",
"latvia": "region",
"library mood": "genre",
"links": "misc",
"lithuania": "region",
"ludvikovsky": "artist",
"maria codrianu": "artist",
"melodia": "artist",
"melodiya": "artist",
"mix": "misc",
"modo": "artist",
"moldavia": "region",
"moldova": "region",
"motorcycle": "misc",
"movie": "misc",
"musical": "genre",
"muslim magomayev": "artist",
"my": "misc",
"oktava": "artist",
"orchestra": "genre",
"orchestra groove": "genre",
"orera": "artist",
"orizont": "artist",
"pakhmutova": "composer",
"pesnyary": "artist",
"plamya": "artist",
"polad bulbuloglu": "composer",
"pop": "genre",
"poyushie serdca": "artist",
"progressive": "genre",
"psychedelic": "genre",
"qaya": "artist",
"raimonds pauls": "composer",
"reggae": "genre",
"rock": "genre",
"rock atelye": "artist",
"russia": "region",
"rybnikov": "composer",
"saarsalu": "artist",
"samotsveti": "artist",
"sampling": "misc",
"saulsky": "composer",
"sci-fi": "misc",
"shake": "genre",
"soul": "genre",
"soulviet": "misc",
"sovremennik": "artist",
"space funk": "genre",
"surf": "genre",
"syabry": "artist",
"tajikistan": "region",
"theatre": "genre",
"tonis magi": "artist",
"tukhmanov": "composer",
"turkmenistan": "region",
"twist'n'beat": "genre",
"ukraine": "region",
"uno naissoo": "composer",
"uzbekistan": "region",
"vainshtein": "artist",
"vasilkov": "artist",
"vdokhnovenie": "artist",
"verasy": "artist",
"veselye rebyata": "artist",
"via 75": "artist",
"vigners": "artist",
"vitamiin": "artist",
"vodograi": "artist",
"ye-ye": "genre",
"zodiac": "artist",
"russia": "region",
"ukraine": "region",
"moldova": "region",
"belarus": "region",
"armenia": "region",
"azerbaijan": "region",
"georgia": "region",
"estonia": "region",
"latvia": "region",
"lithuania": "region",
"kazakhstan": "region",
"tajikistan": "region",
"turkmenistan": "region",
"uzbekistan": "region",
"kyrgyzstan": "region",
}