# -*- coding: utf-8 -*-

tag_data = {
  "jazz": [
    {
      "tag"      : u"kazhlayev",
      "title"    : u"Murad Kazhlayev",
      "title_ru" : u"",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"garanyan",
      "title"    : u"Georgy Garanyan",
      "title_ru" : u"Георгий Гаранян",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"shaqaryan",
      "title"    : u"Stepan Shaqaryan",
      "title_ru" : u"Степан Шакарян",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"vapirov",
      "title"    : u"Anatoly Vapirov",
      "title_ru" : u"Анатолий Вапиров",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"melodia",
      "title"    : u"Melodiya",
      "title_ru" : u"Ансамбль Мелодия",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"nazaruk",
      "title"    : u"Igor Nazaruk",
      "title_ru" : u"Игорь Назарук",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"orbelyan",
      "title"    : u"Konstantin Orbelyan",
      "title_ru" : u"Константин Орбелян",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"goloschekin",
      "title"    : u"David Goloschekin",
      "title_ru" : u"Давид Голощекин",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"brill",
      "title"    : u"Igor Brill",
      "title_ru" : u"Игорь Бриль",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"weinstein",
      "title"    : u"Iosif Weinstein",
      "title_ru" : u"Иосиф Вайнштейн",
      "descr_en" : u"A conductor of a band of his name known for their swinging jazz style.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"sovremennik",
      "title"    : u"Sovremennik",
      "title_ru" : u"Ансамбль Современник п/у Анатолия Кролла",
      "descr_en" : u"A jazz ensemble conducted by Anatoly Kroll. "
                   u"They backed pop singers like Yuri Antonov as well as recorded several super groove tracks "
                   u"some of which were influenced by Polish band \"No To Co\" I believe.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"vigners",
      "title"    : u"Ivars Vigners",
      "title_ru" : u"Иварс Вигнерс",
      "descr_en" : u"A conductor of Latvian orchestras having recorded many easy instrumental tracks. "
                   u"He is also a film music composer. Not well known to the public excepting his native Latvia may be.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"babayev",
      "title"    : u"Rafiq Babayev",
      "title_ru" : u"Рафик Бабаев",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"boomerang",
      "title"    : u"Boomerang",
      "title_ru" : u"Бумеранг",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"dustar",
      "title"    : u"Dustar",
      "title_ru" : u"Дустар",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"kuman",
      "title"    : u"Jaan Kuman",
      "title_ru" : u"Яан Куман",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"saarsalu",
      "title"    : u"Lembit Saarsalu",
      "title_ru" : u"Лембит Саарсалу",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"ludvikovsky",
      "title"    : u"Vadim Ludvikovsky",
      "title_ru" : u"Оркестр п/у Вадима Людвиковского",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"kuman",
      "title"    : u"Jaan Kuman",
      "title_ru" : u"Яан Куман",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"melodiya",
      "title"    : u"Melodiya",
      "title_ru" : u"Ансамбль Мелодия",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"garanian",
      "title"    : u"Georgy Garanyan",
      "title_ru" : u"Георгий Гаранян",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"arsenal",
      "title"    : u"Arsenal",
      "title_ru" : u"Арсенал",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"jazz-comfort",
      "title"    : u"Jazz Comfort",
      "descr_en" : u"A Russian jazz collective playing solo and backing vocalists too. They has recorded a jazz seven only. ",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"straume",
      "title"    : u"Egils Straume",
      "title_ru" : u"Эгилс Страуме",
      "descr_en" : u"A Latvian conductor of a jazz combo and sax player also.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"paulus",
      "title"    : u"Tiit Paulus",
      "descr_en" : u"A famous Estonian guitarist used to play with different ensembles including Jaan Kuman's one. "
                   u"A session musician also. ",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"sato",
      "title"    : u"Sato",
      "title_ru" : u"Сато",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"allegro",
      "title"    : u"Allegro",
      "title_ru" : u"Аллегро",
      "descr_en" : u"A Russian jazz-fusion, jazz-rock ensemble led by Nikolay Levinovsky.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
],
  "series": [
    {
      "tag"      : u"jazz-78",
      "title"    : u"Jazz-78",
      "title_ru" : u"Джаз-78",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"melodiya-x",
      "title"    : u"Melodiya %%",
      "title_ru" : u"",
      "descr_en" : u"Is a series of mixes dedicated to non-USSR artists.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"tantsurutme",
      "title"    : u"Tantsurütme 7\"s",
      "title_ru" : u"Танцевальные ритмы",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
],

  "region": [
    {
      "tag"      : u"armenia",
      "title"    : u"armenia",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"ukraine",
      "title"    : u"ukraine",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"azerbaijan",
      "title"    : u"azerbaijan",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"latvia",
      "title"    : u"latvia",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"belarus",
      "title"    : u"belarus",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"moldavia",
      "title"    : u"moldavia",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"estonia",
      "title"    : u"estonia",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"kazakhstan",
      "title"    : u"kazakhstan",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"georgia",
      "title"    : u"georgia",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"uzbekistan",
      "title"    : u"uzbekistan",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"foreign",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"lithuania",
      "title"    : u"lithuania",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"azerbayjan",
      "title"    : u"azerbayjan",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"tajikistan",
      "title"    : u"Tajikistan",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"kyrgyzstan",
      "title"    : u"kyrgyzstan",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"moldova",
      "title"    : u"moldova",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"russia",
      "title"    : u"russia",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"turkmenistan",
      "title"    : u"turkmenistan",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
],

"modern": [
    {
      "tag"      : u"yuri",
      "title"    : u"U&amp;1989",
      "descr_en" : u"A record collector and donator for this blog.",
      "descr_ru" : u"",
      "urls"     : u"https://soundcloud.com/u1989",
    },
    {
      "tag"      : u"jan-kit",
      "title"    : u"Jan-Kit",
      "descr_en" : u"A DJ for b-boy battles, b-boy himself, turntablist, author of breaking and hip-hop tracks and vinyl collector from Kazakhstan. "
                   u"Known as DJ Jankie earlier. ",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"schmoltz",
      "title"    : u"Schmoltz",
      "descr_en" : u"Шмольц",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"eln",
      "title"    : u"ELN",
      "descr_en" : u"A DJ, hip-hop beatmaker, vinyl collector, drummer and a leader of deep funk band The Soul Surfers "
                   u"from Nizhny Novgorod, Russia. "
                   u"He had recorded one of the most impressive soviet groove mix called Sovok. ",
      "descr_ru" : u"",
      "urls"     : [ 'http://thesoulsurfers.ru/', 'http://vk.com/thesoulsurfers' ],
    },
    {
      "tag"      : u"tengiz",
      "title"    : u"TenDJiz",
      "descr_en" : u"A hip-hop producer and beat maker from Saint Petersburg then Moscow now Miami. "
                   u"He's responsible for several top-class Russian hip-hop projects. "
                   u"He's the author of the first soviet groove mix ever. "
                   u"As DJ SoULviet he has produced three dope mash-up mixes blending soviet jazz/soul beats with American rapping. ",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"mr-and-7",
      "title"    : u"Mr. And-7",
      "descr_en" : u"A vinyl collector, house DJ (as Jay-D), funk-soul DJ (as Mr. And-7) from Moscow.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"weedska",
      "title"    : u"Weedska",
      "descr_en" : u"Vinyl collector and DJ from Lithuania.",
      "descr_ru" : u"",
      "urls"     : [ 'http://www.mixcloud.com/weedska/' ],
    },
    {
      "tag"      : u"steady-rock",
      "title"    : u"Steady Rock",
      "descr_en" : u"A DJ for b-boy battles, b-boy breaks music maker and vinyl collector from Ukraine.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"yan-shrimp",
      "title"    : u"Yan Shrimp",
      "descr_en" : u"A vinyl collector, DJ, b-boy coach and b-boy himself from Moscow.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
],

  "misc": [
    {
      "tag"      : u"movie",
    },
    {
      "tag"      : u"dear-boy",
    },
    {
      "tag"      : u"ensembles",
    },
    {
      "tag"      : u"sci-fi",
    },
    {
      "tag"      : u"motorcycle",
    },
    {
      "tag"      : u"best",
    },
    {
      "tag"      : u"mix",
    },
    {
      "tag"      : u"soulviet",
    },
    {
      "tag"      : u"all-tracks",
    },
    {
      "tag"      : u"info",
    },
    {
      "tag"      : u"links",
    },
    {
      "tag"      : u"my",
    },
    {
      "tag"      : u"composers",
    },
    {
      "tag"      : u"sampling",
    },
    {
      "tag"      : u"my-rip",
    },
    {
      "tag"      : u"video",
    },
    {
      "tag"      : u"recognize",
    },
    {
      "tag"      : u"modern",
    },
    {
      "tag"      : u"spoken",
    },
],

  "vocalist": [
    {
      "tag"      : u"magomayev",
      "title"    : u"Muslim Magomayev",
      "title_ru" : u"Муслим Магомаев",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"vedisheva",
      "title"    : u"Aida Vedisheva",
      "title_ru" : u"Аида Ведишева",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"pugachova",
      "title"    : u"Alla Pugachova",
      "title_ru" : u"Алла Пугачёва",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"pyekha",
      "title"    : u"Edita Piekha",
      "title_ru" : u"Эдита Пьеха",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"codrianu",
      "title"    : u"Maria Codrianu",
      "title_ru" : u"Мария Кодриану",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"magi",
      "title"    : u"Tõnis Mägi",
      "title_ru" : u"Тынис Мяги",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"kuut",
      "title"    : u"Marju Kuut",
      "title_ru" : u"Марью Куут",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"joala",
      "title"    : u"Jaak Joala",
      "title_ru" : u"Яак Йоала",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
],

  "composer": [
    {
      "tag"      : u"shwartz",
      "title"    : u"Isaac Shwartz",
      "title_ru" : u"Исаак Шварц",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"tukhmanov",
      "title"    : u"David Tukhmanov",
      "title_ru" : u"Давид Тухманов",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"gevorgyan",
      "title"    : u"Yevgeny Gevorgyan",
      "title_ru" : u"Евгений Геворгян",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"krylatov",
      "title"    : u"Yevgeny Krylatov",
      "title_ru" : u"Евгений Крылатов",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"bulbuloglu",
      "title"    : u"Polad Bülbüloğlu",
      "title_ru" : u"Полад Бюль-бюль Оглы",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"zatsepin",
      "title"    : u"Alexander Zatsepin",
      "title_ru" : u"Александр Зацепин",
      "descr_en" : u"A top soviet composer known for his pop songs as well as for film works especially Leonid Gaidai's comedies. "
                   u"Uncommonly he had his own recording studio in Moscow. "
                   u"He is also known for his experiments with irregular music instruments and original sounds. ",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"gladkov",
      "title"    : u"Gennadiy Gladkov",
      "title_ru" : u"Геннадий Гладков",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"kalnins",
      "title"    : u"Imants Kalniņš",
      "title_ru" : u"Имантс Калнынш",
      "descr_en" : u"The most known Latvian composer working in a variety of styles - pop music, classical music and film scores. "
                   u"He was behind groups 2xBBM, Menuets since the late 60's and Turaidas Roze in the 80's. ",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"pauls",
      "title"    : u"Raimonds Pauls",
      "title_ru" : u"Раймонд Паулс",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"rychkov",
      "title"    : u"Boris Rychkov",
      "title_ru" : u"Борис Рычков",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"rybnikov",
      "title"    : u"Alexey Rybnikov",
      "title_ru" : u"Алексей Рыбников",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"pakhmutova",
      "title"    : u"Alexandra Pakhmutova",
      "title_ru" : u"Александра Пахмутова",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"kuprevicius",
      "title"    : u"Giedrius Kuprevicius",
      "title_ru" : u"Гедриус Купревичус",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"naissoo",
      "title"    : u"Uno Naissoo",
      "title_ru" : u"Уно Наиссоо",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"gladkov",
      "title"    : u"Gennady Gladkov",
      "title_ru" : u"Геннадий Гладков",
      "descr_en" : u"A Russian composer known for his film scores.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"saulsky",
      "title"    : u"Yuri Saulsky",
      "title_ru" : u"Юрий Саульский",
      "descr_en" : u"A Russian composer best known for his pop songs. "
                   u"For us he has recorded some jazz tracks and scores for theatrical shows. ",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"katenin",
      "title"    : u"Alexander Katenin",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"gazizov",
      "title"    : u"Robert Gazizov",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"ojakaar",
      "title"    : u"Valter Ojakäär",
      "title_ru" : u"Вальтер Оякяэр",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
],

  "time": [
    {
      "tag"      : u"70s",
      "title"    : u"seventies",
    },
    {
      "tag"      : u"60s",
      "title"    : u"sixties",
    },
    {
      "tag"      : u"80s",
      "title"    : u"eighties",
    },
],

  "genre": [
    {
      "tag"      : u"ye-ye",
      "title"    : u"yé-yé",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    }, {
      "tag"      : u"big-beat",
      "title"    : u"",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    }, {
      "tag"      : u"eurocult",
      "title"    : u"euro cult",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"funk",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"orchestra-groove",
      "title"    : u"orchestra groove",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"psychedelic",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"pop",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"eurocrime",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"disco",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"soul",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"jazz-funk",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"jazz",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"twist'n'beat",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"library-mood",
      "title"    : u"library mood",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"jazz-groove",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"beat",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"art-rock",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"space-funk",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"happy-euro",
      "title"    : u"happy euro",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"shake",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"surf",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"garage",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"big beat",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"easy",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"electronica",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"electro",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"rock",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"musical",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"progressive",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"ambient",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"jazz-rock",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"groove",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"blues",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"folk",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"groove-beats",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"theatre",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"orchestra",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"reggae",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"bossa",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"bboybreaks",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"jazz-fusion",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
],

  "ensemble": [
    {
      "tag"      : u"abc",
      "title"    : u"ABC",
      "title_ru" : u"",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"vodograi",
      "title"    : u"Vodograi",
      "title_ru" : u"Водограй",
      "descr_en" : u"An Ukrainian pop ensemble had been using folk motives widely as well as the most of Ukrainian bands.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"orioni",
      "title"    : u"Orioni",
      "title_ru" : u"Ориони",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"veselye-rebyata",
      "title"    : u"Veselye Rebyata",
      "title_ru" : u"ВИА Веселые ребята",
      "descr_en" : u"A top Russian ensemble led by Pavel Slobodkin. It was banded 1966 and was active for 25 years.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"poyushie-serdca",
      "title"    : u"Poyushie Serdtsa",
      "title_ru" : u"ВИА Поюшие сердца",
      "descr_en" : u"Another top Russian pop ensemble banded 1971 by Viktor Wekstein.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"gradsky",
      "title"    : u"Alexander Gradsky",
      "title_ru" : u"Александр Градский и ансамбль \"Скоморохи\"",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"avilov",
      "title"    : u"Rhythm",
      "title_ru" : u"ВИА Ритм п/у Авилова",
      "descr_en" : u"An instrumental ensemble conducted by Alexander Avilov. They are known for backing soviet pop-diva Alla Pugacheva."
                   u"They recorded an AP instrumental disco covers LP well known among collectors.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"plamya",
      "title"    : u"Plamya",
      "title_ru" : u"ВИА Пламя",
      "descr_en" : u"A top Russian pop ensemble known for working with composer Alexandra Pakhmutova.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"qaya",
      "title"    : u"Qaya",
      "title_ru" : u"Вокальный квартет Гая",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"vasilkov",
      "title"    : u"Vladimir Vasilkov",
      "title_ru" : u"Владимир Васильков",
      "descr_en" : u"A drummer best known for his recording sessions for Alexander Gradsky. Conducted a jazz ensemble also.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"samotsveti",
      "title"    : u"Samotsvety",
      "title_ru" : u"Самоцветы",
      "descr_en" : u"A top Russian pop ensemble banded 1971 by Yuri Malikov.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"electron",
      "title"    : u"Electron",
      "title_ru" : u"Электрон",
      "descr_en" : u"One of the first bands in USSR playing surf music since 1964. "
                   u"Later it was rebanded as \"New Electron\". Led by Valery Prikazchikov. ",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"verasy",
      "title"    : u"Verasy",
      "title_ru" : u"Верасы",
      "descr_en" : u"A top Belarussian pop ensemble.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"eolika",
      "title"    : u"Eolika",
      "title_ru" : u"Эолика",
      "descr_en" : u"A Latvian band. Firstly it was banded 1966 by students playing beat and kinda psyche music. "
                   u"Then they get lost for a decade and appeared again at 1980 playing light pop and disco music. "
                   u"That new formation is  only known to the people. ",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"zodiac",
      "title"    : u"Zodiac",
      "title_ru" : u"Зодиак",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"orizont",
      "title"    : u"Orizont",
      "title_ru" : u"Оризонт",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"golubye-gitary",
      "title"    : u"Golubye Gitary",
      "title_ru" : u"Голубые Гитары",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"rock-atelye",
      "title"    : u"Rock Atelye",
      "title_ru" : u"Рок-Ателье",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"modo",
      "title"    : u"Modo",
      "title_ru" : u"Модо",
      "descr_en" : u"A Latvian pop and disco band led by Raimonds Pauls and then by Zigmars Liepins. "
                   u"Mirdza Zievere and Imants Vanzovic used to sing there. ",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"vitamiin",
      "title"    : u"Vitamiin",
      "title_ru" : u"Витамин",
      "descr_en" : u"An Estonian pop band backing different vocalists as well as recording independently. "
                   u"Under name \"Uus Generatsioon\" the same men used to perform highly professional progressive music. ",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"dos-mukasan",
      "title"    : u"Dos-Mukasan",
      "title_ru" : u"Дос–Мукасан",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"disco-petrenko",
      "title"    : u"Disco Band",
      "title_ru" : u"Оркестр и вокальная группа Диско",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"vdokhnovenie",
      "title"    : u"Vdokhnovenie",
      "title_ru" : u"Вдохновенье",
      "descr_en" : u"A less known vocal oriented ensemble from Moscow. Banded 1976. Only several EP's has been recorded.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"iveriya",
      "title"    : u"Iveriya",
      "title_ru" : u"Иверия",
      "descr_en" : u"A band from Georgia. They made many groove things but got too soft in the 80's.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"poyushie-gitary",
      "title"    : u"Poyushie Gitary",
      "title_ru" : u"Поюшие Гитары",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"fix",
      "title"    : u"Fix",
      "title_ru" : u"Фикс",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"syabry",
      "title"    : u"Syabry",
      "title_ru" : u"Сябры",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"75",
      "title"    : u"75",
      "title_ru" : u"ВИА 75",
      "descr_en" : u"An ensemble from Georgia banded 1975 by ex-leader of famous \"Orera\". "
                   u"They recorded several dope groove tracks but then got too soft, fucking eighties.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"orera",
      "title"    : u"Orera",
      "title_ru" : u"Орэра",
      "descr_en" : u"A famous ensemble from Georgia. Buba Kikabidze used to play drums there before he become a super popular film actor.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"pesnyary",
      "title"    : u"Pesnyary",
      "title_ru" : u"Песняры",
      "descr_en" : u"A top band from Belarus. They got famous since 1970 arranging Belarussian folk songs in a modern progressive way.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"oktava",
      "title"    : u"Oktava",
      "title_ru" : u"Октава",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"ariel",
      "title"    : u"Ariel",
      "title_ru" : u"Ариэль",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"estradines-melodijos",
      "title"    : u"Estradinės Melodijos",
      "title_ru" : u"Эстрадные мелодии",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"dielo",
      "title"    : u"Dielo",
      "descr_en" : u"An ensemble from Georgia. Formed 1962 they started as a vocal group.",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"morozov",
      "title"    : u"Yuri Morozov",
      "title_ru" : u"Юрий Морозов",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"psycho",
      "title"    : u"Psycho",
      "title_ru" : u"Психо",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
    {
      "tag"      : u"laine",
      "title"    : u"Laine",
      "title_ru" : u"Эстрадный ансамбль Лайне",
      "descr_en" : u"",
      "descr_ru" : u"",
      "urls"     : u"",
    },
]
}