# -*- coding: utf-8 -*-

tag_table =\
[
    [u"isaac shwartz"      , u"composer" , u"Isaac Shwartz"      , u"Исааc Шwартз"       ],
    [u"70s"                , u"time"     , u"70's"               , u""                   ],
    [u"movie"              , u"misc"     , u""                   , u""                   ],
    [u"ye-ye"              , u"genre"    , u""                   , u""                   ],
    [u"60s"                , u"time"     , u"60's"               , u""                   ],
    [u"funk"               , u"genre"    , u""                   , u""                   ],
    [u"armenia"            , u"region"   , u"armenia"            , u""                   ],
    [u"orchestra groove"   , u"genre"    , u""                   , u""                   ],
    [u"tukhmanov"          , u"composer" , u"David Tukhmanov"    , u"Давид Тухманов"     ],
    [u"vodograi"           , u"ensemble" , u"Vodograi"           , u"Водограи"           ],
    [u"dear boy"           , u"misc"     , u""                   , u""                   ],
    [u"psychedelic"        , u"genre"    , u""                   , u""                   ],
    [u"ensembles"          , u"misc"     , u""                   , u""                   ],
    [u"ukraine"            , u"region"   , u"ukraine"            , u""                   ],
    [u"veselye rebyata"    , u"ensemble" , u"Veselye Rebyata"    , u"Веселyе Ребята"     ],
    [u"poyushie serdca"    , u"ensemble" , u"Poyushie Serdtsa"   , u"Поюшие Сердца"      ],
    [u"evgeny gevorgyan"   , u"composer" , u"Yevgeny Gevorgyan"  , u"Yевгенy Геворгян"   ],
    [u"sci-fi"             , u"misc"     , u""                   , u""                   ],
    [u"krylatov"           , u"composer" , u"Yevgeny Krylatov"   , u"Yевгенy Крyлатов"   ],
    [u"motorcycle"         , u"misc"     , u""                   , u""                   ],
    [u"garanyan"           , u"jazz"     , u"Georgy Garanyan"    , u"Георгy Гаранян"     ],
    [u"azerbaijan"         , u"region"   , u"azerbaijan"         , u""                   ],
    [u"polad bulbuloglu"   , u"composer" , u"Polad Bulbuloglu"   , u"Полад Булбулоглу"   ],
    [u"muslim magomayev"   , u"vocalist" , u"Muslim Magomayev"   , u"Муслим Магомаyев"   ],
    [u"gradsky"            , u"ensemble" , u"Alexander Gradsky"  , u"Алеxандер Градский" ],
    [u"best"               , u"misc"     , u""                   , u""                   ],
    [u"melodia"            , u"jazz"     , u"Melodiya"           , u"Мелодия"            ],
    [u"alexander zatsepin" , u"composer" , u"Alexander Zatsepin" , u"Алеxандер Зацепин"  ],
    [u"aida vedisheva"     , u"vocalist" , u"Aida Vedisheva"     , u"Аида Ведишева"      ],
    [u"pop"                , u"genre"    , u""                   , u""                   ],
    [u"gennadiy gladkov"   , u"composer" , u"Gennadiy Gladkov"   , u"Геннадий Гладков"   ],
    [u"eurocrime"          , u"genre"    , u""                   , u""                   ],
    [u"disco"              , u"genre"    , u""                   , u""                   ],
    [u"avilov"             , u"ensemble" , u"Avilov"             , u"Авилов"             ],
    [u"alla pugachova"     , u"vocalist" , u"Alla Pugachova"     , u"Алла Пугачова"      ],
    [u"80s"                , u"time"     , u"80's"               , u""                   ],
    [u"soul"               , u"genre"    , u""                   , u""                   ],
    [u"plamya"             , u"ensemble" , u"Plamya"             , u"Пламя"              ],
    [u"igor nazaruk"       , u"jazz"     , u"Igor Nazaruk"       , u"Игор Назарук"       ],
    [u"jazz-funk"          , u"genre"    , u""                   , u""                   ],
    [u"jazz"               , u"genre"    , u""                   , u""                   ],
    [u"imants kalnins"     , u"composer" , u"Imants Kalnins"     , u"Иманц Калнинс"      ],
    [u"latvia"             , u"region"   , u"latvia"             , u""                   ],
    [u"edita pyekha"       , u"vocalist" , u"Edita Piekha"       , u"Едита Пиеха"        ],
    [u"qaya"               , u"ensemble" , u"Qaya"               , u"Qая"                ],
    [u"mix"                , u"misc"     , u""                   , u""                   ],
    [u"soulviet"           , u"misc"     , u""                   , u""                   ],
    [u"vasilkov"           , u"ensemble" , u"Vladimir Vasilkov"  , u"Владимир Василков"  ],
    [u"samotsveti"         , u"ensemble" , u"Samotsvety"         , u"Самоцветий"         ],
    [u"electron"           , u"ensemble" , u"Electron"           , u"Елеcтрон"           ],
    [u"twist'n'beat"       , u"genre"    , u""                   , u""                   ],
    [u"konstantin orbelian", u"jazz"     , u"Konstantin Orbelyan", u"Константин Орбелян" ],
    [u"belarus"            , u"region"   , u"belarus"            , u""                   ],
    [u"verasy"             , u"ensemble" , u"Verasy"             , u"Верасий"            ],
    [u"raimonds pauls"     , u"composer" , u"Raimonds Pauls"     , u"Раимондс Паулс"     ],
    [u"library mood"       , u"genre"    , u""                   , u""                   ],
    [u"jazz groove"        , u"genre"    , u""                   , u""                   ],
    [u"beat"               , u"genre"    , u""                   , u""                   ],
    [u"eolika"             , u"ensemble" , u"Eolika"             , u"Еолика"             ],
    [u"david goloschekin"  , u"jazz"     , u"David Goloschekin"  , u"Давид Голощекин"    ],
    [u"art-rock"           , u"genre"    , u""                   , u""                   ],
    [u"space funk"         , u"genre"    , u""                   , u""                   ],
    [u"zodiac"             , u"ensemble" , u"Zodiac"             , u"Зодиаc"             ],
    [u"moldavia"           , u"region"   , u"moldavia"           , u""                   ],
    [u"maria codrianu"     , u"vocalist" , u"Maria Codrianu"     , u"Мариа Cодриану"     ],
    [u"orizont"            , u"ensemble" , u"Orizont"            , u"Оризонт"            ],
    [u"happy euro"         , u"genre"    , u""                   , u""                   ],
    [u"golubye gitary"     , u"ensemble" , u"Golubye Gitary"     , u"Голубyе Гитарий"    ],
    [u"shake"              , u"genre"    , u""                   , u""                   ],
    [u"surf"               , u"genre"    , u""                   , u""                   ],
    [u"rock atelye"        , u"ensemble" , u"Rock Atelye"        , u"Роcк Ателyе"        ],
    [u"all tracks"         , u"misc"     , u""                   , u""                   ],
    [u"info"               , u"misc"     , u""                   , u""                   ],
    [u"modo"               , u"ensemble" , u"Modo"               , u"Модо"               ],
    [u"dj jankie"          , u"modern"   , u"Jan-Kit"            , u""                   ],
    [u"estonia"            , u"region"   , u"estonia"            , u""                   ],
    [u"vitamiin"           , u"ensemble" , u"Vitamiin"           , u"Витамиин"           ],
    [u"kazakhstan"         , u"region"   , u"kazakhstan"         , u""                   ],
    [u"dos-mukasan"        , u"ensemble" , u"Dos-Mukasan"        , u"Дос–Мукасан"        ],
    [u"garage"             , u"genre"    , u""                   , u""                   ],
    [u"georgia"            , u"region"   , u"georgia"            , u""                   ],
    [u"disco band"         , u"ensemble" , u"Disco Band"         , u"Дисcо Банд"         ],
    [u"links"              , u"misc"     , u""                   , u""                   ],
    [u"vdokhnovenie"       , u"ensemble" , u"Vdokhnovenie"       , u"Вдохновение"        ],
    [u"iveriya"            , u"ensemble" , u"Iveriya"            , u"Иверия"             ],
    [u"boris rychkov"      , u"composer" , u"Boris Rychkov"      , u"Борис Рyчков"       ],
    [u"poyushie-gitary"    , u"ensemble" , u"Poyushie Gitary"    , u"Поюшие Гитарий"     ],
    [u"uzbekistan"         , u"region"   , u"uzbekistan"         , u""                   ],
    [u"big beat"           , u"genre"    , u""                   , u""                   ],
    [u"easy"               , u"genre"    , u""                   , u""                   ],
    [u"electronica"        , u"genre"    , u""                   , u""                   ],
    [u"electro"            , u"genre"    , u""                   , u""                   ],
    [u"igor brill"         , u"jazz"     , u"Igor Brill"         , u"Игор Брилл"         ],
    [u"rybnikov"           , u"composer" , u"Alexey Rybnikov"    , u"Алеxеy Рyбников"    ],
    [u"rock"               , u"genre"    , u""                   , u""                   ],
    [u"my"                 , u"misc"     , u""                   , u""                   ],
    [u"foreign"            , u"region"   , u""                   , u""                   ],
    [u"pakhmutova"         , u"composer" , u"Alexandra Pakhmutova", u"Алеxандра Пахмутова"],
    [u"musical"            , u"genre"    , u""                   , u""                   ],
    [u"lithuania"          , u"region"   , u"lithuania"          , u""                   ],
    [u"kuprevicius"        , u"composer" , u"Giedrius Kuprevicius", u"Гиедриус Купревиcиус"],
    [u"vainshtein"         , u"jazz"     , u"Iosif Vainshtein"   , u"Иосиф Ваинштеин"    ],
    [u"uno naissoo"        , u"composer" , u"Uno Naissoo"        , u"Уно Наиссоо"        ],
    [u"fix"                , u"ensemble" , u"Fix"                , u"Фиx"                ],
    [u"syabry"             , u"ensemble" , u"Syabry"             , u"Сябрий"             ],
    [u"progressive"        , u"genre"    , u""                   , u""                   ],
    [u"ambient"            , u"genre"    , u""                   , u""                   ],
    [u"gladkov"            , u"composer" , u"Gennady Gladkov"    , u"Геннадy Гладков"    ],
    [u"composers"          , u"misc"     , u""                   , u""                   ],
    [u"jazz-rock"          , u"genre"    , u""                   , u""                   ],
    [u"via 75"             , u"ensemble" , u"75"                 , u"ВИА 75"             ],
    [u"sovremennik"        , u"jazz"     , u"Sovremennik"        , u"Современник"        ],
    [u"sampling"           , u"misc"     , u""                   , u""                   ],
    [u"vigners"            , u"jazz"     , u"Ivars Vigners"      , u"Иварс Вигнерс"      ],
    [u"groove"             , u"genre"    , u""                   , u""                   ],
    [u"eln"                , u"modern"   , u"ELN"                , u""                   ],
    [u"orera"              , u"ensemble" , u"Orera"              , u"Орера"              ],
    [u"blues"              , u"genre"    , u""                   , u""                   ],
    [u"folk"               , u"genre"    , u""                   , u""                   ],
    [u"pesnyary"           , u"ensemble" , u"Pesnyary"           , u"Песнярий"           ],
    [u"groove beats"       , u"genre"    , u""                   , u""                   ],
    [u"oktava"             , u"ensemble" , u"Oktava"             , u"Октава"             ],
    [u"theatre"            , u"genre"    , u""                   , u""                   ],
    [u"tonis magi"         , u"vocalist" , u"Tonis Magi"         , u"Тонис Маги"         ],
    [u"orchestra"          , u"genre"    , u""                   , u""                   ],
    [u"saulsky"            , u"composer" , u"Yuri Saulsky"       , u"Юри Саулский"       ],
    [u"azerbayjan"         , u"region"   , u"azerbayjan"         , u""                   ],
    [u"babayev"            , u"jazz"     , u"Rafiq Babayev"      , u"Рафиq Бабаyев"      ],
    [u"boomerang"          , u"jazz"     , u"Boomerang"          , u"Боомеранг"          ],
    [u"dustar"             , u"jazz"     , u"Dustar"             , u"Дустар"             ],
    [u"jaan-kuman"         , u"jazz"     , u"Jaan Kuman"         , u"Йаан Куман"         ],
    [u"saarsalu"           , u"jazz"     , u"Lembit Saarsalu"    , u"Лембит Саарсалу"    ],
    [u"reggae"             , u"genre"    , u""                   , u""                   ],
    [u"bossa"              , u"genre"    , u""                   , u""                   ],
    [u"ludvikovsky"        , u"jazz"     , u"Vadim Ludvikovsky"  , u"Вадим Лудвиковский" ],
    [u"my-rip"             , u"misc"     , u""                   , u""                   ],
    [u"bboybreaks"         , u"genre"    , u""                   , u""                   ],
    [u"ariel"              , u"ensemble" , u"Ariel"              , u"Ариел"              ],
    [u"tajikistan"         , u"region"   , u"Tajikistan"         , u""                   ],
    [u"jaan kuman"         , u"jazz"     , u"Jaan Kuman"         , u"Йаан Куман"         ],
    [u"kyrgyzstan"         , u"region"   , u"kyrgyzstan"         , u""                   ],
    [u"moldova"            , u"region"   , u"moldova"            , u""                   ],
    [u"russia"             , u"region"   , u"russia"             , u""                   ],
    [u"melodiya"           , u"jazz"     , u"Melodiya"           , u"Мелодия"            ],
    [u"kuman"              , u"jazz"     , u"Jaan Kuman"         , u"Йаан Куман"         ],
    [u"turkmenistan"       , u"region"   , u"turkmenistan"       , u""                   ],
    [u"garanian"           , u"jazz"     , u"Georgy Garanyan"    , u"Георгy Гаранян"     ],
]

tag_hash = {}
for row in tag_table:
    name = row[0]
    cat = row[1]
    title = row[2]
    if not title: title = name
    title_ru = row[3]
    tag_hash[name] = {
        'category': cat,
        'title':    title,
        'title_ru': title_ru
    }
