application: sovietraregroove
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: themes/birman/static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin
  script: admin.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /importdata/.*
  script: importdata.py
  login: admin

- url: /font.*
  script: fontgen/fontgen.py

- url: /.*
  script: blog.py

