application: sovietraregroove
version: 3
runtime: python
api_version: 1

builtins:
- appstats: on

handlers:

- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /static
  static_dir: themes/grid/static
  expiration: 30d

- url: /static2
  static_dir: static2

- url: /rss.xml
  static_files: html/special/rss.xml
  upload: html/special/rss.xml
  mime_type: text/xml

- url: /search.html
  static_files: html/special/search.html
  upload: html/special/search.html
  mime_type: text/html

- url: /comments/edit/(.+)
  script: comments.py
  login: admin
  
- url: /comments/(.+)
  script: comments.py
  
- url: /(.+)
  static_files: html/\1
  upload: html/(.+)
  mime_type: text/html; charset=utf-8
