application: sovietraregroove
version: 3
runtime: python
api_version: 1

handlers:

- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /preview/.*
  script: preview.py

- url: /static
  static_dir: themes/grid/static
  expiration: 30d

- url: /rss
  static_files: html/special/rss.xml
  upload: html/special/rss.xml
  mime_type: text/xml

- url: /(.+)
  static_files: html/\1
  upload: html/(.+)
  mime_type: text/html; charset=utf-8
