application: sgcomhrd
version: 3
runtime: python
api_version: 1

builtins:
- appstats: on

handlers:

- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /static
  static_dir: themes/grid/static
  expiration: 30d

- url: /static2
  static_dir: static2

- url: /rss.xml
  static_files: html/special/rss.xml
  upload: html/special/rss.xml
  mime_type: text/xml

- url: /search.html
  static_files: html/special/search.html
  upload: html/special/search.html
  mime_type: text/html

- url: /comments/edit/(.+)
  script: comments.py
  login: admin
  
- url: /comments/(.+)
  script: comments.py
  
- url: /favicon.ico
  static_files: html/favicon.png
  upload: html/favicon.png

- url: /(.+\.html)
  static_files: html/\1
  upload: html/(.+\.html)
  mime_type: text/html; charset=utf-8

- url: /(.+\.txt)
  static_files: html/\1
  upload: html/(.+\.txt)
  mime_type: text/plain; charset=utf-8

# used to redirect
# from http://2.sovietraregroove.appspot.com/dj-willderness-magnitizdat-mix
# to http://www.sovietgroove.com/dj-willderness-magnitizdat-mix.html
- url: /(.+)
  static_files: 404.html
  upload: 404.html
  mime_type: text/html; charset=utf-8
