application: sovietraregroove
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:

- url: /static
  static_dir: themes/grid/static
  expiration: 30d

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin/importdata/.*
  script: operablogimport/importdata.py
  login: admin

- url: /admin.*
  script: admin.py
  login: admin

#- url: /font.*
#  script: fontgen/fontgen.py

# no admin-mode to be testable
- url: /rss
  script: blog.py

- url: /.*
  script: blog.py
  #login: admin
